kind: AWSCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-cluster
spec:
  region: us-east-1
---
kind: Cluster
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: test-cluster
  namespace: default
spec:
  infrastructureRef:
    kind: AWSCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    name: test-cluster
    namespace: default
---
kind: KubeadmConfig
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-config
spec:
  initConfiguration:
    nodeRegistration:
      name: '{{ ds.meta_data.hostname }}'
      kubeletExtraArgs:
        cloud-provider: aws
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: aws
    controllerManager:
      extraArgs:
        cloud-provider: aws
  files:
    - path: /hello.txt
      content: hello
      permissions: '0644'
      owner: detiber:detiber
  ntp:
    enabled: true
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org
  users:
    - name: detiber
      gecos: detiber
      groups: wheel
      sshAuthorizedKeys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsBAPUMwg/8M9S4Kjh0jnVILNvLjE1mcyCNx5k5d+03yY6nFdUJwJuUbXhqz/Rm+LwwRme4GXgSQKBxWu6YU0+QYMZZJUDdSy2+O47OKe/UzrdOAIOyW/OvTsJ/mgt9whK01DsdrgfKZteGiKw1fYEkQdmzB31/Hqyv+rKH7plGwPUTEwcs0zWj+PZekUKM5XGbM0L8ky9HDlIrzRy7rMdAS6ip6HybXNAU+yFlD8US3OTrmrJUMBnI0Ox+Yq2gTHb1K/r6pBhTAMDUdqHE1zADy8azEGX0Cifn+qOf642DiDvJCE1u9cYpRPnQ0JSCN65iF/Nm5v95s05F0gjtZ2/ detiber@yeti.local.detiberus.net"
    - name: user2
      gecos: Fake User
---
kind: AWSMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-machine
spec:
  instanceType: t3.large
---
kind: Machine
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: test-machine
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster
    cluster.x-k8s.io/control-plane: "true"
    set: controlplane
spec:
  bootstrap:
    configRef:
      kind: KubeadmConfig
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      namespace: default
      name: test-config
  infrastructureRef:
    kind: AWSMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    namespace: default
    name: test-machine
  version: "v1.14.4"
