---
kind: KubeadmConfigTemplate
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
metadata:
  name: kubeadmconfigtemplate-a-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.hostname }}'
          kubeletExtraArgs:
            cloud-provider: aws
---
kind: AWSMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: awsmachinetemplate-a-md-0
spec:
  template:
    spec:
      instanceType: t3.large
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
---
kind: MachineDeployment
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: machinedeployment-a-md-0
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: cluster-a
    nodepool: nodepool-0
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: cluster-a
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: cluster-a
        nodepool: nodepool-0
    spec:
      version: "v1.15.3"
      bootstrap:
        configRef:
          kind: KubeadmConfigTemplate
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          namespace: default
          name: kubeadmconfigtemplate-a-md-0
      infrastructureRef:
        kind: AWSMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        namespace: default
        name: awsmachinetemplate-a-md-0
