kind: AWSCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-a
spec:
  region: us-east-1
---
kind: Cluster
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: test-a
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    kind: AWSCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    name: test-a
    namespace: default
---
kind: KubeadmConfig
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-a
spec:
  initConfiguration:
    nodeRegistration:
      name: '{{ ds.meta_data.hostname }}'
      kubeletExtraArgs:
        cloud-provider: aws
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: aws
    controllerManager:
      extraArgs:
        cloud-provider: aws
---
kind: AWSMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-a
spec:
  instanceType: t3.large
  iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
---
kind: Machine
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: test-a
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: test-a
    cluster.x-k8s.io/control-plane: "true"
    set: controlplane
spec:
  bootstrap:
    configRef:
      kind: KubeadmConfig
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      namespace: default
      name: test-a
  infrastructureRef:
    kind: AWSMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    namespace: default
    name: test-a
  version: "v1.14.4"
