kind: DockerCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-d
---
kind: Cluster
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: test-d
  namespace: default
spec:
  infrastructureRef:
    kind: DockerCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    name: test-d
    namespace: default
---
kind: KubeadmConfig
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-d
spec:
  clusterConfiguration: {}
---
kind: DockerMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: test-d
---
kind: Machine
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: test-d
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: test-d
    cluster.x-k8s.io/control-plane: "true"
    set: controlplane
spec:
  bootstrap:
    configRef:
      kind: KubeadmConfig
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      namespace: default
      name: test-d
  infrastructureRef:
    kind: DockerMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    namespace: default
    name: test-d
  version: "v1.14.4"
